id: A571C07C1
base_file: f0F14.txt
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:07:45.289467
  last_modified_at: 2022-06-05 20:07:45.289474
