id: A571C07C1
base_file: fBB11.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:07:45.295158
  last_modified_at: 2022-06-05 20:07:45.295163
